courses/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.course, name="course"),
    path('<id>/', views.course_details),
    path('create/course/', views.createCourse),
    path('user/list/', views.userCourse),
    path('user/<id>/', views.userCourseDetails),
]


courses/models.py
from django.db import models

#from embed_video.fields import EmbedVideoField

#from django.contrib.auth.models import User

#from users.models import Account


# Create your models here.
class Course(models.Model):
    #user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    image = models.ImageField(null=True, blank=True)
    image_url = models.CharField(max_length=2000, null=True, blank=True)
    #course = EmbedVideoField(null=True)
    url = models.CharField(max_length=2000, null=True, blank=True)
    note = models.CharField(max_length=2000, null=True, blank=True)

    def __str__(self):
        return self.title
        
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except :
            url = ''
        return url

class Topic(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)
    topic = models.CharField(max_length=2000)
    image_url = models.CharField(max_length=2000, null=True, blank=True)
    #video_url = EmbedVideoField(null=True)
    other_url = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.topic

        
        
class Notification(models.Model):
	title = models.CharField(max_length=200, null=True)
	notice = models.CharField(max_length=2000)
	
	def __str__(self):
		return self.notice
	
class Books(models.Model):
	image = models.ImageField(null=True, blank=True)
	title = models.CharField(max_length=200)
	note = models.CharField(max_length=10000, null=True, blank=True)
	image_url = models.CharField(max_length=2000, null=True, blank=True)
	url = models.CharField(max_length=200)
	
	def __str__(self):
		return self.title

	@property
    def imageURL(self):
        try:
            url = self.image.url
        except :
            url = ''
        return url
	
class Events(models.Model):
	event = models.ImageField(null=True, blank=True)
	title = models.CharField(max_length=200)
	note = models.CharField(max_length=10000, null=True, blank=True)
	url = models.CharField(max_length=200)
	image_url = models.CharField(max_length=2000, null=True, blank=True)
	#videourl = EmbedVideoField(null=True, blank=True)
	
	
	def __str__(self):
		return self.url


	@property
    def imageURL(self):
        try:
            url = self.image.url
        except :
            url = ''
        return url
	
	

	
	
	
	

	

courses/templates/courses/course.html
{% extends 'courses/index.html' %}
{% load static %}
{% load embed_video_tags %}
{% block content %}

<h2 class="section-heading">{{course.title}}</h2>

<h4>{{course.title}}</h4>
<section>
  {% for topic in course.topic_set.all %}
      <div class="card">
        <div class="card-image">
          {%video topic.video_url%}
        </div>
        <div class="card-description">
          <a href="{{topic.other_url}}">View More</h4>
        </div>
      </div>
  {% endfor %}
</section>
{% endblock content %}

courses/templates/courses/courseCreate.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Register an account</h1>
        <label for="title">Title</label>
        <input type="text" name="title"  placeholder="Title" required autofocus>
        <label for="image"></label>
        <input type="file" name="image" value="fileupload" id="fileupload">
        <label for="note">Title</label>
        <input type="text" name="note"  placeholder="Note" required>

        {% for field in registration_form %}
        <p>{% for error in field.errors %}<p style="color: red">{{ error }}</p>{% endfor %}</p>
        {% endfor %}
        {% if registration_form.non_field_errors %}
            <div>
            	<p>{{registration_form.non_field_errors}}</p>
            </div>
        {% endif %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Upload</button>
    </form>
</body>
</html>



courses/templates/courses/courseDetail.html
{% extends 'courses/index.html' %}
{% load static %}
{% load embed_video_tags %}
{% block content %}
  <a href="/" class="page-heading">BACK</a>
  <div id="post-container">
      <section id="blogpost">
        <div class="card">
          <div class="card-meta-blogpost">
          </div>
          <div class="card-image">
            <img src="{{course.imageURL}}" alt="Card Image">
          </div>
          <div class="card-description">
            <h1>{{course.title}}</h1>
            <br>
            <h2>{{course.note}}</h2>
          </div>
        </div>
      </section>

      <aside id="sidebar">
        <h3>Course Videos</h3>
        {% for topic in course.topic_set.all %}
          <div class="video-card">
            <div class="video-image">
              {%video topic.video_url%}
            </div>
            <div class="card-description">
              <a href="{{topic.other_url}}">View More</h4>
            </div>
          </div>
        {% endfor %}
      </aside>
    </div>
  </div>
{% endblock content %}

courses/templates/courses/courses.html
{% extends 'courses/index.html' %}
{% load static %}
{% block content %}
<a href="#">
  <h2 class="section-heading">HOME</h2>
</a>
<section>
  {% for course in courses %}
  <div class="card">
    <div class="card-image">
      <a href="/course/{{course.id}}">
        <img class="course-img" src="{{course.imageURL}}" alt="Card Image">
      </a>
    </div>
    <div class="card-description">
      <a href="#">
        <h3>{{course.title}}</h3>
      </a>
      <a href="/course/{{course.id}}" class="btn-readmore">View</a>
    </div>
  </div>
  {% endfor %}
</section>
{% endblock content %}

courses/templates/courses/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Digi-Learn</title>
</head>

<body>
    <div id="slideout-menu">
        <ul>
            <li>
                <a href="#">Account</a>
            </li>
            <li>
                <a href="/">Courses</a>
            </li>
        </ul>
    </div>

    <nav>
        <div id="logo-img">
            <a href="#">
            </a>
        </div>
        <div id="menu-icon">
            <i class="fas fa-bars">Menu</i>
        </div>
        <ul>
            <li>
                <a href="#">Account</a>
            </li>
            <li>
                <a href="/">Courses</a>
            </li>
            <li>
                <div id="search-icon">
                    <i class="fas fa-search"></i>
                </div>
            </li>
        </ul>
    </nav>

    <div id="searchbox">
        <input type="text" placeholder="Search Here">
    </div>
    <main>
        {% block content %}
        {% endblock %}

    </main>
    <footer>
        <div id="right-footer">
            <i class="fas fa-facebook"><h2>About</h2></i>
        </div>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

courses/templates/courses/userCourseDetail.html
{% extends 'courses/index.html' %}
{% load static %}
{% load embed_video_tags %}
{% block content %}
  <a href="/" class="page-heading">BACK</a>
  <div id="post-container">
      <section id="blogpost">
        <div class="card">
          <div class="card-meta-blogpost">
          </div>
          <div class="card-image">
            <img src="{{course.imageURL}}" alt="Card Image">
          </div>
          <div class="card-description">
            <h1>{{course.title}}</h1>
            <br>
            <h2>{{course.note}}</h2>
            <div>
              <h1>Upload New Video</h1>
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" name="topic"  placeholder="Title" required autofocus>
                <input type="text" name="video_url" placeholder="Video Url" id="fileupload">
                <input type="text" name="other_url"  placeholder="Other Url" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit">Upload</button> 
              </form>
            </div>
          </div>
        </div>
      </section>

      <aside id="sidebar">
        <h3>Course Videos</h3>
        {% for topic in course.topic_set.all %}
          <div class="video-card">
            <div class="video-image">
              {%video topic.video_url%}
            </div>
            <div class="card-description">
              <a href="{{topic.other_url}}">View More</h4>
            </div>
          </div>
        {% endfor %}
      </aside>
    </div>
  </div>
{% endblock content %}

courses/templates/courses/userCourses.html
{% extends 'courses/index.html' %}
{% load static %}
{% block content %}
<a href="#">
  <h2 class="section-heading">HOME</h2>
</a>
<section>
  {% for course in courses %}
  <div class="card">
    <div class="card-image">
      <a href="/course/{{course.id}}">
        <img class="course-img" src="{{course.imageURL}}" alt="Card Image">
      </a>
    </div>
    <div class="card-description">
      <a href="#">
        <h3>{{course.title}}</h3>
      </a>
      <a href="/course/user/{{course.id}}" class="btn-readmore">Edit</a>
    </div>
  </div>
  {% endfor %}
</section>
{% endblock content %}